spring.application.name=colorado-pool-finder-api

spring.datasource.url=jdbc:mysql://localhost:3306/pool_finder
spring.datasource.username=root
spring.datasource.password=password

#swap out update for create on full reset of data
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true